// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include <WiFi.h>
#include "time.h"
#include <stdio.h>
#include "freertos/FreeRTOS.h"

const char* ntpServer = "pool.ntp.org";
const long  gmtOffset_sec = 0;
const int   daylightOffset_sec = 3600;

const char DEVICE_LOGIN_NAME[]  = "9b6664c8-3320-4d3e-a8bd-8014cc94c9e6";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onRelayChange();
void onSetTimestampChange();
void onGetTimestampChange();
void NTPCode(void *pvParameters);

bool led;
bool relay;
char sec[2];
char minute[2];
char hour[2];
char date[2];
char mon[2];
char year[4];
const int pinRelay = 26;

CloudTime get_timestamp;
CloudTime set_timestamp;

void initProperties() {
  pinMode(pinRelay, OUTPUT);
  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(led, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(relay, READWRITE, ON_CHANGE, onRelayChange);
  ArduinoCloud.addProperty(get_timestamp, READ, ON_CHANGE, onGetTimestampChange);
  ArduinoCloud.addProperty(set_timestamp, READWRITE, ON_CHANGE, onSetTimestampChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
